export type CommandCategory =
  | "Core"
  | "Repository tools"
  | "Repository intelligence"
  | "Utility";
export type CommandRole =
  | "bootstrap"
  | "repo-intelligence"
  | "governance"
  | "remediation"
  | "compatibility"
  | "utility";
export type CommandLifecycle =
  | "canonical"
  | "compatibility"
  | "utility"
  | "planned-reference";
export type CommandDiscoverability =
  | "primary"
  | "secondary"
  | "hidden-compatibility";

export type CommandMetadata = {
  name: string;
  description: string;
  category: CommandCategory;
  role: CommandRole;
  lifecycle: CommandLifecycle;
  discoverability: CommandDiscoverability;
  onboardingPriority: number | null;
  canonicalSequence: number | null;
  productFacing: boolean;
  exampleArgs: string;
  machineReadable: boolean;
};

export const commandMetadata: CommandMetadata[] = [
  {
    name: "analyze",
    description: "Analyze project stack",
    category: "Core",
    role: "compatibility",
    lifecycle: "compatibility",
    discoverability: "hidden-compatibility",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "analyze --json",
    machineReadable: true,
  },
  {
    name: "pilot",
    description:
      "Run one-command external baseline analysis workflow for a target repository",
    category: "Core",
    role: "bootstrap",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: 'pilot --repo "./target-repo" --json',
    machineReadable: true,
  },
  {
    name: "verify",
    description: "Detect repository state and extract governance invariants",
    category: "Core",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 8,
    canonicalSequence: 8,
    productFacing: true,
    exampleArgs: "verify --baseline main --format sarif --out .playbook/verify.sarif",
    machineReadable: true,
  },
  {
    name: "plan",
    description: "Transform findings into a structured remediation model",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 9,
    canonicalSequence: 9,
    productFacing: true,
    exampleArgs: "plan --json",
    machineReadable: true,
  },
  {
    name: "lanes",
    description:
      "Derive deterministic lane-state from .playbook/workset-plan.json",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "lanes --json",
    machineReadable: true,
  },
  {
    name: "workers",
    description:
      "Assign deterministic proposal-only workers, derive launch authorization, and submit worker results from lane-state/workset artifacts",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "workers assign --json",
    machineReadable: true,
  },
  {
    name: "orchestrate",
    description:
      "Generate deterministic orchestration lane artifacts for a goal or tasks-file workset",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: 'orchestrate --goal "ship capability" --lanes 3 --format both',
    machineReadable: true,
  },

  {
    name: "execute",
    description:
      "Execute orchestration lanes through the execution supervisor runtime",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "execute --json",
    machineReadable: true,
  },
  {
    name: "cycle",
    description:
      "Run the hardened execution primitives as one deterministic cycle orchestration pass",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "cycle --json",
    machineReadable: true,
  },
  {
    name: "apply",
    description: "Enforce and materialize deterministic plan tasks",
    category: "Core",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 10,
    canonicalSequence: 10,
    productFacing: true,
    exampleArgs: "apply --from-plan .playbook/plan.json",
    machineReadable: true,
  },
  {
    name: "commit",
    description: "Atomically run release sync, stage all changes, and execute git commit",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "commit -m \"chore: update\"",
    machineReadable: false,
  },
  {
    name: "analyze-pr",
    description:
      "Analyze local branch/worktree changes with deterministic PR intelligence",
    category: "Repository tools",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "analyze-pr --json",
    machineReadable: true,
  },

  {
    name: "review-pr",
    description:
      "Run governed read-only PR review by composing analyze-pr, improve, and policy evaluate outputs",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "review-pr --json",
    machineReadable: true,
  },
  {
    name: "doctor",
    description:
      "Diagnose repository health by aggregating verify, risk, docs, and index analyzers",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "doctor --fix --dry-run",
    machineReadable: true,
  },
  {
    name: "diagram",
    description: "Generate deterministic architecture Mermaid diagrams",
    category: "Repository tools",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "diagram --repo . --out docs/ARCHITECTURE_DIAGRAMS.md",
    machineReadable: false,
  },
  {
    name: "patterns",
    description:
      "Inspect pattern knowledge graph data and review promotion candidates",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "patterns list --json",
    machineReadable: true,
  },
  {
    name: "docs",
    description: "Audit documentation governance surfaces and contracts",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "docs audit --json",
    machineReadable: true,
  },
  {
    name: "audit",
    description:
      "Audit deterministic architecture guardrails and platform hardening controls",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "audit architecture --json",
    machineReadable: true,
  },
  {
    name: "rules",
    description: "List loaded verify and analyze rules",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "rules --json",
    machineReadable: true,
  },
  {
    name: "schema",
    description: "Print JSON Schemas for Playbook CLI command outputs",
    category: "Repository tools",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "schema verify --json",
    machineReadable: true,
  },
  {
    name: "context",
    description:
      "Print deterministic CLI and architecture context for tools and agents",
    category: "Repository tools",
    role: "bootstrap",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 3,
    canonicalSequence: 3,
    productFacing: true,
    exampleArgs: "context --json",
    machineReadable: true,
  },
  {
    name: "ai-context",
    description:
      "Print deterministic AI bootstrap context for Playbook-aware agents",
    category: "Repository tools",
    role: "bootstrap",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 1,
    canonicalSequence: 1,
    productFacing: true,
    exampleArgs: "ai-context --json",
    machineReadable: true,
  },
  {
    name: "ai-contract",
    description:
      "Print deterministic AI repository contract for Playbook-aware agents",
    category: "Repository tools",
    role: "bootstrap",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 2,
    canonicalSequence: 2,
    productFacing: true,
    exampleArgs: "ai-contract --json",
    machineReadable: true,
  },

  {
    name: "ai",
    description:
      "Emit proposal-only AI artifacts from deterministic context and contract surfaces",
    category: "Repository tools",
    role: "bootstrap",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "ai propose --json --out .playbook/ai-proposal.json",
    machineReadable: true,
  },

  {
    name: "test-triage",
    description: "Parse deterministic test failure triage guidance from captured Vitest/pnpm logs",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "test-triage --input .playbook/ci-failure.log --json",
    machineReadable: true,
  },
  {
    name: "test-fix-plan",
    description: "Generate a bounded remediation plan from a deterministic test-triage artifact",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "test-fix-plan --from-triage .playbook/test-triage.json --json",
    machineReadable: true,
  },
  {
    name: "test-autofix",
    description: "Orchestrate deterministic test diagnosis, bounded repair, apply, and narrow-first verification",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "test-autofix --input .playbook/ci-failure.log --json",
    machineReadable: true,
  },
  {
    name: "remediation-status",
    description:
      "Inspect recent test-autofix remediation history, repeat-policy decisions, and retry guidance",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "remediation-status --json",
    machineReadable: true,
  },
  {
    name: "rendezvous",
    description:
      "Create/status/release-dry-run artifact rendezvous readiness from canonical remediation artifacts",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "rendezvous create --json",
    machineReadable: true,
  },
  {
    name: "interop",
    description:
      "Inspect and run remediation-first Playbook↔Lifeline interop contracts from rendezvous artifacts",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "interop health --json",
    machineReadable: true,
  },
  {
    name: "ignore",
    description:
      "Suggest and safely apply ranked .playbookignore recommendations",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 12,
    canonicalSequence: 12,
    productFacing: true,
    exampleArgs: "ignore suggest --repo ../target-repo --json",
    machineReadable: true,
  },

  {
    name: "contracts",
    description:
      "Emit deterministic contract registry for schemas, artifacts, and roadmap status",
    category: "Repository tools",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "contracts --json",
    machineReadable: true,
  },
  {
    name: "changelog",
    description:
      "Generate, validate, and safely append deterministic WHAT/WHY changelog entries",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "changelog generate --base HEAD~1 --format markdown",
    machineReadable: true,
  },
  {
    name: "release",
    description: "Plan deterministic installable release/version decisions from repo evidence",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "release plan --json --out .playbook/release-plan.json",
    machineReadable: true,
  },
  {
    name: "index",
    description: "Generate machine-readable repository intelligence index",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 4,
    canonicalSequence: 4,
    productFacing: true,
    exampleArgs: "index --json",
    machineReadable: true,
  },
  {
    name: "graph",
    description:
      "Summarize machine-readable repository knowledge graph from .playbook/repo-graph.json",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "graph --json",
    machineReadable: true,
  },
  {
    name: "query",
    description:
      "Query machine-readable repository intelligence from .playbook/repo-index.json",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 5,
    canonicalSequence: 5,
    productFacing: true,
    exampleArgs: "query modules --json",
    machineReadable: true,
  },
  {
    name: "deps",
    description: "Print module dependency graph from .playbook/repo-index.json",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "deps workouts --json",
    machineReadable: true,
  },
  {
    name: "ask",
    description:
      "Answer repository questions from machine-readable intelligence context",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 7,
    canonicalSequence: 7,
    productFacing: true,
    exampleArgs: 'ask "where should a new feature live?" --repo-context --json',
    machineReadable: true,
  },
  {
    name: "explain",
    description:
      "Explain rules, modules, or architecture from repository intelligence",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: 6,
    canonicalSequence: 6,
    productFacing: true,
    exampleArgs: "explain architecture --json",
    machineReadable: true,
  },
  {
    name: "demo",
    description:
      "Show the official Playbook demo repository and guided first-run workflow",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "demo",
    machineReadable: false,
  },
  {
    name: "init",
    description: "Initialize playbook docs/config",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "init",
    machineReadable: true,
  },
  {
    name: "fix",
    description: "Apply safe, deterministic autofixes for verify findings",
    category: "Utility",
    role: "compatibility",
    lifecycle: "compatibility",
    discoverability: "hidden-compatibility",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "fix --dry-run",
    machineReadable: true,
  },
  {
    name: "status",
    description:
      "Show deterministic repository health and adoption readiness status",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "status --json",
    machineReadable: true,
  },
  {
    name: "receipt",
    description:
      "Ingest explicit execution results into receipt, updated-state, and next-queue",
    category: "Utility",
    role: "utility",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "receipt ingest execution-results.json --json",
    machineReadable: true,
  },
  {
    name: "upgrade",
    description: "Check and apply explicit local Playbook dependency upgrades",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "upgrade --json",
    machineReadable: true,
  },
  {
    name: "route",
    description:
      "Classify tasks and emit deterministic proposal-only execution plans for task-specific routing decisions",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: 'route "summarize current repo state" --json',
    machineReadable: true,
  },
  {
    name: "architecture",
    description:
      "Verify subsystem registry ownership and architecture mapping integrity",
    category: "Repository tools",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "architecture verify --json",
    machineReadable: true,
  },
  {
    name: "promote",
    description: "Promote reviewed repo-local stories and reusable pattern candidates into canonical artifacts",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "promote story repo/<repo-id>/story-candidates/<candidate-id> --json",
    machineReadable: true,
  },
  {
    name: "story",
    description: "Manage the canonical repo-local story backlog state",
    category: "Repository tools",
    role: "remediation",
    lifecycle: "canonical",
    discoverability: "primary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "story list --json",
    machineReadable: true,
  },
  {
    name: "session",
    description: "Manage repo-scoped session memory and snapshot workflows",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: false,
    exampleArgs: "session show --json",
    machineReadable: true,
  },
  {
    name: "learn",
    description:
      "Draft deterministic knowledge candidates from local diff and repository intelligence",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "learn draft --json --out .playbook/knowledge/candidates.json",
    machineReadable: true,
  },
  {
    name: "memory",
    description:
      "Inspect, review, and curate repository memory artifacts with explicit human-reviewed doctrine promotion",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "memory events --json",
    machineReadable: true,
  },
  {
    name: "improve",
    description:
      "Generate deterministic improvement candidates from memory events and learning-state signals",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "improve --json",
    machineReadable: true,
  },
  {
    name: "knowledge",
    description:
      "Inspect read-only knowledge artifacts and provenance surfaces",
    category: "Repository intelligence",
    role: "repo-intelligence",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "knowledge list --json",
    machineReadable: true,
  },

  {
    name: "security",
    description: "Inspect deterministic security baseline findings and summary",
    category: "Utility",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "security baseline summary --json",
    machineReadable: true,
  },
  {
    name: "telemetry",
    description:
      "Inspect deterministic repository/process telemetry and compact cross-run learning summaries",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "telemetry learning --json",
    machineReadable: true,
  },
  {
    name: "policy",
    description:
      "Evaluate improvement proposals against governed runtime evidence (read-only control-plane)",
    category: "Utility",
    role: "governance",
    lifecycle: "canonical",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "policy evaluate --json",
    machineReadable: true,
  },
  {
    name: "agent",
    description:
      "Read runtime control-plane records and run plan-backed dry-run previews",
    category: "Utility",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "agent run --from-plan .playbook/plan.json --dry-run --json",
    machineReadable: true,
  },
  {
    name: "observer",
    description:
      "Manage deterministic local observer registry and read-only local API server",
    category: "Repository tools",
    role: "utility",
    lifecycle: "utility",
    discoverability: "secondary",
    onboardingPriority: null,
    canonicalSequence: null,
    productFacing: true,
    exampleArgs: "observer serve --port 4300",
    machineReadable: true,
  },
];

export const getCommandMetadata = (name: string): CommandMetadata | undefined =>
  commandMetadata.find((command) => command.name === name);
