import { createHash } from 'node:crypto';
import type { FleetAdoptionWorkQueue, AdoptionWorkItem, WorkQueueParallelGroup } from './workQueue.js';

export type ExecutionPlanWaveId = 'wave_1' | 'wave_2';

export type CodexExecutionWave = {
  wave_id: ExecutionPlanWaveId;
  purpose: string;
  repos: string[];
  worker_lanes: string[];
  completion_criteria: string;
};

export type CodexExecutionWorkerLane = {
  lane_id: string;
  wave: ExecutionPlanWaveId;
  recommended_command_family: WorkQueueParallelGroup;
  repo_ids: string[];
  dependencies: string[];
  parallel_safe: boolean;
  merge_conflict_risk: 'low' | 'medium' | 'high';
  rationale: string;
};

export type CodexPromptGovernanceNotes = {
  rules: string[];
  patterns: string[];
  failure_modes: string[];
};

export type CodexExecutionPrompt = {
  prompt_id: string;
  wave: ExecutionPlanWaveId;
  lane_id: string;
  repo_id: string;
  objective: string;
  implementation_plan: string[];
  files_to_modify: string[];
  verification_steps: string[];
  documentation_updates: string[];
  governance_notes: CodexPromptGovernanceNotes;
  prompt: string;
};

export type CodexExecutionBlockedFollowup = {
  item_id: string;
  repo_id: string;
  unmet_dependencies: string[];
  unlocks_after: 'wave_1_and_wave_2';
};

export type FleetCodexExecutionPlan = {
  schemaVersion: '1.0';
  kind: 'fleet-adoption-codex-execution-plan';
  generated_at: string;
  source_queue_digest: string;
  waves: CodexExecutionWave[];
  worker_lanes: CodexExecutionWorkerLane[];
  codex_prompts: CodexExecutionPrompt[];
  execution_notes: string[];
  blocked_followups: CodexExecutionBlockedFollowup[];
};

const PURPOSE_BY_WAVE: Record<ExecutionPlanWaveId, string> = {
  wave_1: 'Execute zero-dependency adoption steps that are unblocked now.',
  wave_2: 'Execute items unlocked directly by Wave 1 completion.'
};

const COMPLETION_BY_WAVE: Record<ExecutionPlanWaveId, string> = {
  wave_1: 'All Wave 1 lanes complete with command outputs captured per repo.',
  wave_2: 'All Wave 2 lanes complete and no lane has unmet same-wave dependencies.'
};

const GOVERNANCE_BY_GROUP: Record<WorkQueueParallelGroup, CodexPromptGovernanceNotes> = {
  'connect lane': {
    rules: ['Rule: Keep adoption execution read-only at planning time; no automatic mutation.'],
    patterns: ['Pattern: Execute one deterministic command family per lane to minimize operator ambiguity.'],
    failure_modes: ['Failure Mode: Cross-repo drift when repos are not connected through a single observer registry context.']
  },
  'init lane': {
    rules: ['Rule: Initialize Playbook before index/verify/apply workflows.'],
    patterns: ['Pattern: Batch same-family init commands across repos in a dedicated lane.'],
    failure_modes: ['Failure Mode: Bootstrap drift when init is skipped and later commands infer missing state.']
  },
  'index lane': {
    rules: ['Rule: Index outputs are authoritative prerequisites for repository intelligence commands.'],
    patterns: ['Pattern: Run index as a dedicated lane before plan-generation families.'],
    failure_modes: ['Failure Mode: Agent drift when planning starts from stale or missing repo-index artifacts.']
  },
  'verify/plan lane': {
    rules: ['Rule: Deterministic remediation must follow verify -> plan before apply.'],
    patterns: ['Pattern: Keep verify/plan paired in one lane to preserve deterministic evidence continuity.'],
    failure_modes: ['Failure Mode: Plan/apply mismatch when verify and plan are split across incompatible states.']
  },
  'apply lane': {
    rules: ['Rule: Apply is allowed only after prerequisite verify/plan evidence exists.'],
    patterns: ['Pattern: Keep apply lanes PR-sized and isolated by repo to reduce merge conflicts.'],
    failure_modes: ['Failure Mode: Unsafe mutation when apply runs without validated prior governance artifacts.']
  },
  'retry lane': {
    rules: ['Rule: Retry lanes must be derived from canonical updated-state only, never directly from raw receipts.'],
    patterns: ['Pattern: Preserve prompt lineage and command family when emitting deterministic retries.'],
    failure_modes: ['Failure Mode: Split-brain control flow appears when retries are re-derived from readiness instead of updated-state.']
  },
  'replan lane': {
    rules: ['Rule: Stale or superseded execution outcomes must route to deterministic replanning instead of automatic retry.'],
    patterns: ['Pattern: Updated-state replan lanes converge state back through verify -> plan before any further execution.'],
    failure_modes: ['Failure Mode: Reusing a stale plan without replanning can loop execution against superseded state.']
  }
};

const FILE_HINTS_BY_GROUP: Record<WorkQueueParallelGroup, string[]> = {
  'connect lane': ['repo-local governed artifacts / command outputs only'],
  'init lane': ['playbook.config.json (if generated)', '.playbook/**'],
  'index lane': ['.playbook/repo-index.json', '.playbook/repo-graph.json (if generated by workflow)'],
  'verify/plan lane': ['.playbook/verify.json', '.playbook/plan.json'],
  'apply lane': ['repo-local governed artifacts / command outputs only'],
  'retry lane': ['retry the same governed command family recorded in prompt lineage'],
  'replan lane': ['.playbook/verify.json', '.playbook/plan.json']
};

const LANE_PRIORITY: Record<WorkQueueParallelGroup, number> = {
  'connect lane': 0,
  'init lane': 1,
  'index lane': 2,
  'verify/plan lane': 3,
  'apply lane': 4,
  'retry lane': 5,
  'replan lane': 6
};

const mergeRiskForGroup = (group: WorkQueueParallelGroup): 'low' | 'medium' | 'high' => {
  if (group === 'apply lane') return 'high';
  if (group === 'verify/plan lane') return 'medium';
  return 'low';
};

const sortLaneGroups = (left: WorkQueueParallelGroup, right: WorkQueueParallelGroup): number =>
  LANE_PRIORITY[left] - LANE_PRIORITY[right] || left.localeCompare(right);

const sortPromptItems = (left: AdoptionWorkItem, right: AdoptionWorkItem): number =>
  sortLaneGroups(left.parallel_group, right.parallel_group) || left.repo_id.localeCompare(right.repo_id) || left.item_id.localeCompare(right.item_id);

const stableDigest = (queue: FleetAdoptionWorkQueue): string => {
  const normalized = {
    ...queue,
    generated_at: '__stable__'
  };
  return createHash('sha256').update(JSON.stringify(normalized)).digest('hex');
};

const waveItems = (queue: FleetAdoptionWorkQueue): { wave1: AdoptionWorkItem[]; wave2: AdoptionWorkItem[]; blocked: AdoptionWorkItem[] } => {
  const wave1 = queue.work_items.filter((item) => item.dependencies.length === 0);
  const wave1Ids = new Set(wave1.map((item) => item.item_id));
  const dependent = queue.work_items.filter((item) => item.dependencies.length > 0);
  const wave2 = dependent.filter((item) => item.dependencies.every((dependency) => wave1Ids.has(dependency)));
  const wave2Ids = new Set(wave2.map((item) => item.item_id));
  const blocked = dependent.filter((item) => !wave2Ids.has(item.item_id));
  return { wave1, wave2, blocked };
};

const laneIdFor = (wave: ExecutionPlanWaveId, group: WorkQueueParallelGroup): string => `${wave}:${group.replace(/\s+/g, '_').replace('/', '_')}`;

const laneRationale = (group: WorkQueueParallelGroup, wave: ExecutionPlanWaveId): string =>
  `${group} keeps the ${wave} package command-homogeneous and reduces repo overlap inside the same dependency stage.`;

const toPromptText = (input: {
  repoId: string;
  lane: CodexExecutionWorkerLane;
  item: AdoptionWorkItem;
  notes: CodexPromptGovernanceNotes;
}): string => {
  return [
    `Repo: ${input.repoId}`,
    `Wave: ${input.lane.wave}`,
    `Lane: ${input.lane.lane_id}`,
    `Objective: Execute ${input.item.parallel_group} for ${input.repoId} using ${input.item.recommended_command}.`,
    'Constraints: Read-only planning translation only. Do not run commands automatically. Keep changes repo-local and deterministic.',
    'Implementation Plan:',
    `1. Confirm prerequisite dependencies: ${input.item.dependencies.length > 0 ? input.item.dependencies.join(', ') : 'none'}.`,
    `2. Prepare a PR-sized change scoped to ${input.item.parallel_group}.`,
    `3. Execute/record command output manually with: ${input.item.recommended_command}.`,
    'Acceptance Criteria:',
    '1. The repo-local execution package stays within the expected changed paths for this command family.',
    '2. The recommended command output and any required artifacts are recorded deterministically.',
    '3. Any workflow or contract doc change is reflected in documentation updates or reported as blocked.',
    'Expected Changed Paths:',
    ...FILE_HINTS_BY_GROUP[input.item.parallel_group].map((entry) => `- ${entry}`),
    'Expected Unchanged Paths:',
    '- Any repo path outside the expected changed paths for this lane.',
    'Blocked / Skipped Reporting Rules:',
    '- Mutating Codex tasks are not governed unless they declare explicit acceptance criteria.',
    '- Summary text is not proof. Do not report completion unless command output, artifacts, and final diff prove each satisfied criterion.',
    '- If a criterion cannot be completed or a non-listed path would need to change, report blocked, skipped, or failed with the exact path-level reason.',
    'Verification:',
    '1. Confirm command completes successfully.',
    '2. Confirm generated artifacts are deterministic and repo-local.',
    'Documentation updates:',
    '1. Update operator notes/changelog if workflow or contract output changed.',
    `Rule notes: ${input.notes.rules.join(' ')}`,
    `Pattern notes: ${input.notes.patterns.join(' ')}`,
    `Failure Mode notes: ${input.notes.failure_modes.join(' ')}`
  ].join('\n');
};

export const buildFleetCodexExecutionPlan = (
  queue: FleetAdoptionWorkQueue,
  options?: { generatedAt?: string }
): FleetCodexExecutionPlan => {
  const generatedAt = options?.generatedAt ?? new Date().toISOString();
  const { wave1, wave2, blocked } = waveItems(queue);
  const waveById: Record<ExecutionPlanWaveId, AdoptionWorkItem[]> = { wave_1: wave1, wave_2: wave2 };

  const workerLanes: CodexExecutionWorkerLane[] = (['wave_1', 'wave_2'] as const).flatMap((wave) => {
    const byGroup = new Map<WorkQueueParallelGroup, AdoptionWorkItem[]>();
    for (const item of waveById[wave]) {
      byGroup.set(item.parallel_group, [...(byGroup.get(item.parallel_group) ?? []), item]);
    }

    return [...byGroup.entries()]
      .sort((left, right) => sortLaneGroups(left[0], right[0]))
      .map(([group, items]) => ({
        lane_id: laneIdFor(wave, group),
        wave,
        recommended_command_family: group,
        repo_ids: Array.from(new Set(items.map((item) => item.repo_id))).sort((left, right) => left.localeCompare(right)),
        dependencies: Array.from(new Set(items.flatMap((item) => item.dependencies))).sort((left, right) => left.localeCompare(right)),
        parallel_safe: true,
        merge_conflict_risk: mergeRiskForGroup(group),
        rationale: laneRationale(group, wave)
      }));
  });

  const laneLookup = new Map(workerLanes.map((lane) => [`${lane.wave}::${lane.recommended_command_family}`, lane]));

  const prompts: CodexExecutionPrompt[] = (['wave_1', 'wave_2'] as const).flatMap((wave) =>
    waveById[wave]
      .slice()
      .sort(sortPromptItems)
      .map((item) => {
        const lane = laneLookup.get(`${wave}::${item.parallel_group}`);
        if (!lane) {
          throw new Error(`missing lane for item ${item.item_id}`);
        }
        const governanceNotes = GOVERNANCE_BY_GROUP[item.parallel_group];
        const promptId = `${wave}:${item.parallel_group.replace(/\s+/g, '_')}:${item.repo_id}`;
        return {
          prompt_id: promptId,
          wave,
          lane_id: lane.lane_id,
          repo_id: item.repo_id,
          objective: `Advance ${item.repo_id} through ${item.parallel_group} with deterministic, PR-sized execution packaging.`,
          implementation_plan: [
            `Review queue item rationale: ${item.rationale}`,
            `Use command family: ${item.recommended_command}`,
            'Keep scope to one lane and one repo to minimize overlap risk.'
          ],
          files_to_modify: FILE_HINTS_BY_GROUP[item.parallel_group],
          verification_steps: [
            `Validate dependencies are satisfied: ${item.dependencies.length > 0 ? item.dependencies.join(', ') : 'none'}`,
            `Run/record: ${item.recommended_command}`,
            'Confirm outputs remain deterministic and consistent with readiness contracts.'
          ],
          documentation_updates: [
            'Update docs/CHANGELOG.md when command/workflow state changes.',
            'Update operator-facing command docs when output contract changes.'
          ],
          governance_notes: governanceNotes,
          prompt: toPromptText({ repoId: item.repo_id, lane, item, notes: governanceNotes })
        };
      })
  );

  const waves: CodexExecutionWave[] = (['wave_1', 'wave_2'] as const).map((wave) => {
    const items = waveById[wave];
    return {
      wave_id: wave,
      purpose: PURPOSE_BY_WAVE[wave],
      repos: Array.from(new Set(items.map((item) => item.repo_id))).sort((left, right) => left.localeCompare(right)),
      worker_lanes: workerLanes
        .filter((lane) => lane.wave === wave)
        .sort((left, right) => sortLaneGroups(left.recommended_command_family, right.recommended_command_family) || left.lane_id.localeCompare(right.lane_id))
        .map((lane) => lane.lane_id),
      completion_criteria: COMPLETION_BY_WAVE[wave]
    };
  });

  return {
    schemaVersion: '1.0',
    kind: 'fleet-adoption-codex-execution-plan',
    generated_at: generatedAt,
    source_queue_digest: stableDigest(queue),
    waves,
    worker_lanes: workerLanes,
    codex_prompts: prompts,
    execution_notes: [
      'Planner is read-only: it translates queue state into operator execution packaging.',
      'Wave 1 contains only zero-dependency work; Wave 2 contains work unlocked by Wave 1.',
      'Lane grouping is command-family homogeneous to reduce merge conflicts and parallel overlap risk.'
    ],
    blocked_followups: blocked.map((item) => ({
      item_id: item.item_id,
      repo_id: item.repo_id,
      unmet_dependencies: [...item.dependencies],
      unlocks_after: 'wave_1_and_wave_2'
    }))
  };
};
